steps:
  - input: "Deploy?"
    key: "deploy-check"
    fields:
      - select: "decision"
        key: "deploy-decision"
        options:
          - label: "Yes"
            value: "y"
          - label: "No"
            value: "n"
  - label: "Continue"
    depends_on: "deploy-check"
    command: |
      set -xeuo pipefail

      if [ $(buildkite-agent meta-data get deploy-decision) == "y" ]; then
        buildkite-agent pipeline upload .buildkite/03_if_yes.yml
      else
        buildkite-agent pipeline upload .buildkite/04_if_no.yml
      fi
