steps:
  - label: ":heroku: Deployed"
    key: "deployed"
    command: |
      echo "DEPLOYED #${BUILDKITE_BUILD_NUMBER}"
  - label: ":jira: Update JIRA"
    key: "update-jira"
    command: |
      echo "JIRA updated"
  - input: ":slack: Notify?"
    key: "notify-check"
    depends_on:
      - "deployed"
    fields:
      - select: "Notify team on Slack channel?"
        key: "notify-decision"
        options:
          - label: "Yes"
            value: "y"
          - label: "No"
            value: "n"
  - label: "Continue"
    depends_on: "notify-check"
    command: |
      set -xeuo pipefail
      if [ $(buildkite-agent meta-data get notify-decision) == "y" ]; then
        buildkite-agent pipeline upload .buildkite/05_notify.yml
      fi
